<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>True</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ID3.list" />
    <None Remove="ObjectID.list" />
    <EmbeddedResource Include="ID3.list" LogicalName="ID3.list" />
    <EmbeddedResource Include="ObjectID.list" LogicalName="ObjectID.list" />
    <EmbeddedResource Remove="*.resx" />
    <None Include="*.resx" />
    <EmbeddedResource Include="CompiledResources\*.resources" LogicalName="%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="ExaltHelper_Data\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TileID.list">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="lib\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="Microsoft.Bcl.HashCode">
      <HintPath>lib\Microsoft.Bcl.HashCode.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>lib\System.Buffers.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>lib\System.Collections.Immutable.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Formats.Nrbf">
      <HintPath>lib\System.Formats.Nrbf.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>lib\System.Memory.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>lib\System.Numerics.Vectors.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Reflection.Metadata">
      <HintPath>lib\System.Reflection.Metadata.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Resources.Extensions">
      <HintPath>lib\System.Resources.Extensions.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>lib\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>
